# Generated by Django 4.2.16 on 2024-09-30 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koppeeapp', '0002_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='media/services')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
