# Generated by Django 4.2.16 on 2024-09-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koppeeapp', '0003_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='iconlink',
            field=models.URLField(null=True),
        ),
    ]
