# Generated by Django 4.2.16 on 2024-09-30 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koppeeapp', '0004_services_iconlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='iconlink',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
