# Generated by Django 4.2.16 on 2024-09-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koppeeapp', '0006_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('Hot Coffee', 'Hot Coffee'), ('Cold Coffee', 'Cold Coffee')], max_length=100, null=True),
        ),
    ]
