# Generated by Django 4.2.16 on 2024-10-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koppeeapp', '0011_alter_reservation_number_of_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='number_of_guest',
            field=models.IntegerField(max_length=10),
        ),
    ]
